name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.24'

    - name: Build
      run: go build -v github.com/mark-adams/gcp-ip-list/cmd/gcp-ip-list

    - name: Test
      run: go test -v ./...